# Generated by Django 5.2.17 on 2026-09-16 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('series', 'Series')], max_length=16)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('original_title', models.CharField(blank=True, max_length=300)),
                ('original_language', models.CharField(blank=True, max_length=10)),
                ('synopsis', models.TextField(blank=True)),
                ('poster_path', models.CharField(blank=True, max_length=300)),
                ('backdrop_path', models.CharField(blank=True, max_length=300)),
                ('external_vote_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('external_vote_count', models.PositiveIntegerField(blank=True, null=True)),
                ('muratori_rating_average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('muratori_rating_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_editorial_override', models.BooleanField(default=False, help_text='Set once staff hand-edit fields; provider sync must not overwrite them.')),
                ('genres', models.ManyToManyField(blank=True, related_name='media_items', to='catalog.genre')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('tmdb', 'TMDB'), ('imdb', 'IMDb')], max_length=20)),
                ('external_id', models.CharField(max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_ids', to='catalog.mediaitem')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('runtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_details', to='catalog.mediaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SeriesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_air_date', models.DateField(blank=True, null=True)),
                ('last_air_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('returning', 'Returning series'), ('ended', 'Ended'), ('canceled', 'Canceled'), ('in_production', 'In production')], max_length=20)),
                ('number_of_seasons', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('media_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series_details', to='catalog.mediaitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['media_type', 'is_active'], name='catalog_med_media_t_3c4d6c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaitem',
            index=models.Index(fields=['title'], name='catalog_med_title_f102d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='externalid',
            constraint=models.UniqueConstraint(fields=('provider', 'external_id'), name='unique_provider_external_id'),
        ),
        migrations.AddConstraint(
            model_name='externalid',
            constraint=models.UniqueConstraint(fields=('media_item', 'provider'), name='unique_media_item_provider'),
        ),
    ]
